@extends('front_site_without_headernav_footer')

@section('content')
<section class="py-[5%]">
    <div class="px-[15px] w-[98%] mx-auto">
        <div class="flex flex-wrap -mx-[15px]">
            <div class="px-[15px]">
                <div class="iw-terms-conditions-area">
                    <div class="iw-terms-conditions-content">
                        <h2 class="main-heading">OVAL - General Terms and Conditions</h2>
                        <p>NVMCO Group LLC DBA OVAL  is the owner and operator of the OVAL App and the website located at <a href="http://oval.care">www.oval.care</a>. Please read the following, carefully bearing in mind that this Agreement must be read in conjunction with OVAL’s Privacy Policy located at <a href="http://oval.care/legal">www.oval.care/legal.</a></p>
                        <p>These terms, including all agreements, terms, conditions and policies incorporated in
                            this Agreement by reference, together with any legal notices on the Site, shall constitute
                            the entire agreement between you and NVMCO Group LLC.
                        </p>
                        <p><b>IMPORTANT NOTE: If you are under the age of 18, you may not use this app.</b></p>
                        <p><b>LEGAL NOTICE: you agree that any and all disputes or claims you may have at any time with respect to OVAL shall be resolved exclusively through final and binding arbitration, and not by a court or jury. you may find full arbitration and opt-out information at <a href="http://oval.care/legal">www.oval.care/legal.</a></b></p>

                        <h4>1. The Terms</h4>
                        <h4>1.1 Acceptance of Terms</h4>
                        <p>This General Terms and Conditions Agreement (the “Agreement”) sets forth the terms and conditions governing your general use of the OVAL app and the website www.ovalcareL.com and your access to and use of the information, content, and services offered on this app and website (which, collectively constitute the “Services”). By accessing or using this app or website or any of the Services, you accept and agree to be legally bound by this Agreement, as it may be amended or supplemented from time to time (as further described below), and agree to all operating rules and/or policies of Company and the Services that may be published by Company on this Site. All these rules and policies are incorporated into this Agreement by this reference.
                        </p>
                        <p>IF YOU DO NOT ACCEPT THE TERMS OF THIS AGREEMENT, YOU MAY NOT ACCESS THE OVAL APP OR THE SITE OR USE ANY OF ITS SERVICES.</p>
                        <h4>1.2 Right to Modify Terms</h4>
                        <p>OVAL reserves the right to modify the terms of this Agreement at any time at its sole discretion and may post a notice of such changes. If and when the Agreement is modified, you will be subject to the terms of the modified Agreement, and by accessing the OVAL Website or app, you agree to the terms of the modified Agreement, without further notice.</p>
                        <h4>1.3 Term Definitions</h4>
                        <ol>
                            <li>"OVAL Website" means the OVAL Website accessible through the URL www.ovalcare.com among other websites owned and operated by OVAL.</li>
                            <li>“OVAL” means NVMCO Group LLC D/B/A OVAL</li>
                            <li>“Parties” means OVAL and you, collectively.</li>
                            <li>“Party” means either OVAL or you</li>
                            <li>"User Profile" means a profile posted by you on the OVAL Website and/or app.</li>
                            <li>“you,” “your,” and/or “User” means any individuals and/or entities visiting and/or otherwise accessing the OVAL Website and/or app for any reason; said terms may be used interchangeably.</li>
                            <li>“Content” means all information, data, text, software, music, sound, photographs, graphics, videos, messages, tags, or other materials posted and/or otherwise displayed on, to, or at the OVAL Website and/or app. </li>
                            <li>“Personal Information” means, without limitation, any information that identifies or describes an individual, including his or her name, professional licensing information, physical description, age, gender, home address, home telephone number, or education. Personal Information also includes statements made by, or attributed to, a User.</li>
                            <li>“Licensor” or “Licensors” means the individuals who have licensed their online lecture content exclusively to OVAL.</li>
                        </ol>
                        <h4>2. Website and/or App</h4>
                        <h4>2.1 Content Ownership</h4>
                        <p>OVAL is the owner and/or licensee of all OVAL Content posted on or otherwise accessible at or via the OVAL Website and/or app including logos, all designs, text, graphics, pictures, and information. Unless otherwise agreed in writing, you will have a limited one (1) year license (without the right to sublicense) to view the Content for your educational, non-commercial use only. Any copying, reproduction, retransmission, or republication of all, or part, of any Content found on the OVAL Website and/or app  is expressly prohibited, unless OVAL has expressly granted its prior written consent to so reproduce, retransmit, or republish the Content. OVAL reserves all applicable rights in regard to the Content.</p>
                        <p>OVAL may publish or transmit via the OVAL Website and/or app any Content that is owned by third parties. OVAL’s Licensors are the owners of their respective Intellectual Property found on the OVAL Website and/or app that may have licensed their Content to OVAL. Any reproduction, retransmission, or republication of all or part of any Content found on the OVAL Website and/or app is expressly prohibited, unless the owner of the Content has expressly granted its prior written consent to reproduce, retransmit, or republish the material.</p>
                        <h4>2.2 Trademarks</h4>
                        <p>Portions of the OVAL app and/or Website may be customized by enterprise customers to include use of your logo and other trademarks for custom branding. If you choose to use such customization, you agree to grant to OVAL a nonexclusive, non-transferable, revocable right to use and distribute your logos and such additional or replacement buttons, logos, characters, or designs (the "Trademarks") as OVAL may request. You further agree to provide the Trademarks in a format required by OVAL for any online or print promotions. OVAL agrees to use the Trademarks solely in conjunction with the permitted forms of use under this Agreement. Use of the Trademarks does not give OVAL any right, title, or interest in the Trademarks, other than the license rights granted herein. OVAL may not assign, transfer, or sublicense any Trademark right granted herein without your prior written consent.</p>
                        <h4>2.3 Copyright Complaints</h4>
                        <p>If you believe that any Content on the OVAL App and/or Website infringes upon any copyright which you own or control, you or your designee, acting as a “Complaining Party,” may send a notification of such claimed infringement to OVAL to info@ovalcare.com. Please include a description of the work that is allegedly being infringed, and where on the OVAL app and/or Website the work may be found.</p>
                        <h4>2.4 Content Availability</h4>
                        <p>Once you have access to the program on OVAL through the third party that provided you the access, you will have access to the Content for the duration that the third party has agreed to provide you in conjunction with OVAL. After such time, your access to the Content will end. To regain access to the Course, you will have to contact the third party that granted you access. </p>
                        <h4>2.4.2 Subscription</h4>
                        <p>After purchasing a subscription, you will have to renew your subscription to continue your access to the Content. To regain access to the subscription, you will have to contact the third party that subscribed to the OVAL. </p>
                        <h4>2.5 Termination</h4>
                        <p>OVAL reserves the right to terminate, block, or restrict your access to or use of the OVAL Website and/or app for any breach or violation of any term(s) of this Agreement, solely at the discretion of OVAL. </p>
                        <h4>2.6 Equipment</h4>
                        <p>You are responsible for obtaining and maintaining all computer hardware and software needed to access and use the OVAL Website and/or app.</p>
                        <h4>2.7 Internet Speed</h4>
                        <p>We recommend Cable, Broadband Internet, or a company LAN on a T1 or higher to take full advantage of the high-quality video and multimedia that OVAL offers.</p>
                        <h4>2.8 Software Requirements</h4>
                        <p>In order to provide an engaging and interactive experience, our Content/Courses use Flash technology. To watch our Content/Courses, we require our Users to have Flash. Please visit www.adobe.com/products/flashplayer/ to download the newest version of Flash.</p>
                        <h4>3. User Accounts</h4>
                        <h4>3.1 User Responsibility</h4>
                        <p>The OVAL Website and/or app includes the option of allowing a User to create a “User Profile.” Users are wholly responsible for User Content posted, displayed, transmitted, or otherwise made available on or via User Profiles. You are also wholly responsible for ensuring that your use of the OVAL App and/or Website is compliant with the laws and regulations of any applicable jurisdiction. </p>
                        <h4>3.2 Accounts and Passwords</h4>
                        <p>In consideration of your use of the OVAL Website and/or app, you acknowledge that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of the United States or other applicable jurisdiction. you agree to provide accurate, current, and complete information concerning you when providing information to, signing up with, registering for use of, or otherwise providing information to the OVAL App and/or Website and maintain and promptly update the Registration Data to keep it true, current, and complete. If you provide any information that is untrue, inaccurate, not current, or incomplete, or if OVAL has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete, OVAL has the right to suspend or terminate your access to the OVAL Website and/or app and to refuse any and all current or future use of the OVAL Website and/or app, or any portion thereof.</p>
                        <p>You must have your own password to access the OVAL Website and/or app. You are not permitted to provide others access to OVAL Courses using your User Name and Password or another authorized User Name and Password. In the event that OVAL discovers Password sharing, we reserve the right to terminate or block your access to the OVAL Website and/or app. You are responsible for all use of your password(s).</p>
                        <h4>3.3 Linking to OVAL</h4>
                        <p>1. OVAL invites Users to link to our app and/or Website. Linking to OVAL must not improperly connote an affiliation with or an endorsement by OVAL, or otherwise interfere with the operation of the OVAL app and/or Website. Any links should open in a new browser window.</p>
                        <p>2. You must not place OVAL app and/or Website pages in a “frame” within your own Website and/or app without explicit prior written permission from OVAL.</p>
                        <p>3. Although the OVAL Website and/or app may include links providing direct access to other Internet sites, OVAL assumes no responsibility for the Content or information contained on such other sites, and does not exert any editorial or other control over those other sites. OVAL provides no warranties and explicitly disclaims any liability for any Content or other information provided on other sites.</p>
                        <h4>4. Disclaimers</h4>
                        <h4>4.1 Generally</h4>
                        <p>Except as expressly set forth herein, the content of the OVAL Website and/or app (including all OVAL intellectual property, text, materials, software, functions, services, and information made available herein or accessed by means hereof) are provided as is, without warranties of any kind, either express or implied, including without limitation warranties of suitability for a particular purpose. OVAL does not warrant or guarantee uninterrupted access to the OVAL Website and/or app, or any site linked to the OVAL Website and/or app and reserves the right to discontinue Courses or to change the expiration date at any time.</p>
                        <p>Under no circumstances will OVAL be liable in any way for any content, including without limitation any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available via the OVAL Website and/or app, and OVAL makes no guarantees that the content will be accurate, current, or error-free.</p>
                        <p>You assume full responsibility and risk of loss resulting from use of the OVAL Website and/or app and any information on the OVAL Website and/or app. OVAL makes no guarantees about the suitability of any information and its services for any purpose whatsoever. OVAL may provide programs with exercises related to your condition that you can perform at home. As there is a risk of injury with any activity, use caution when performing such exercises. IF YOU EXPERIENCE PAIN OR DISCOMFORT, IMMEDIATELY DISCONTINUE THE EXERCISES AND CONTACT YOUR CLINICIAN OR PHYSICIAN. BY VOLUNTARILY UNDERTAKING ANY EXERCISE IN A PROGRAM PROVIDED BY OVAL, YOU AGREE THAT YOU ASSUME THE RISK OF ANY RESULTING INJURY. OVAL will not be liable for any direct, indirect, consequential, special, exemplary, or other damages or losses that may result.</p>

                        <h4>4.2 Continuing Education Courses</h4>
                        <p>The information and content provided in the Courses are for informational purposes only. OVAL makes no warranties regarding, and bears no liability for, your use of the information and content. Neither OVAL nor the instructor assumes any responsibility for any loss or injury and/or damage to persons or property arising out of the use of the material contained in or related to the online courses. IT IS THE RESPONSIBILITY OF THE TREATING PRACTITIONER, RELYING ON INDEPENDENT EXPERTISE AND KNOWLEDGE OF THE PATIENT, TO DETERMINE THE BEST TREATMENT AND METHOD OF APPLICATION FOR THE PATIENT.</p>
                        <h4>4.3 Recommended Courses</h4>
                        <p>The information and content provided in the recommended courses are for informational purposes only and are not intended to convey or constitute legal advice and should not be relied upon as such. An OVAL recommended course is not a substitute for obtaining advice from a qualified medical professional or practitioner. You should not act upon any such information without first seeking qualified professional counsel on your specific matter. OVAL makes no warranties regarding, and bears no liability for, your use of the information and content. Neither OVAL nor the instructor assumes any responsibility for any loss or injury and/or damage to persons or property arising out of the use of the material contained in or related to the online courses made available by OVAL or third parties through its Website or app. </p>
                        <h4>4.4 Home Exercise Program</h4>
                        <p>YOU AGREE THAT YOU WILL NOT INCLUDE ANY PROTECTED HEALTH INFORMATION IN THE CREATION OF ANY HOME EXERCISE PROGRAM.</p>
                        <h4>5. Limitation of Liability</h4>
                        <p>In no event shall OVAL, its members, officers, affiliates, agents, licensors, employees, or internet service provider(s) (collectively, “representatives”) be liable to you or to any third party for any direct, indirect, incidental, special, or consequential damages whatsoever, including without limitation lost revenue, lost or damaged data, or other commercial or economic loss, whether based in contract, tort (including negligence), or any other theory of liability. The foregoing limitation shall apply even if OVAL or its representatives have been advised or should have known of the possibility of such damage. OVAL’s total liability in any event is limited to the amount, if any, actually paid for use of the OVAL Website and/or app, and you hereby release OVAL and its representatives from any and all obligations, liabilities, and claims in excess of this limitation.</p>
                        <h4>6. Billing</h4>
                        <h4>6.1 Payment Method</h4>
                        <p>Your third party purchased the subscription for you.  Not all Courses are available to subscribers. That depends on the subscription that was purchased for you.  OVAL will not require any credit card information from you. </p>
                        <h4>6.2 Payment Amounts</h4>
                        <h4>6.2.1 Subscription Fees</h4>
                        <p>Please refer to the Subscriptions page for subscription pricing. Your subscription will continue until your third party cancels it. </p>
                        <h4>7. Course Credit Policy</h4>
                        <h4>7.1 Individual Courses</h4>
                        <p>OVAL is committed to providing the highest quality online education for our Users. In the event that OVAL experiences circumstances which render the coursework or learning assessments unavailable to you for a significant period of time, you may choose one (1) of the following:</p>
                        <p>1. Extending the amount of time the Course is available to you for the amount of time the Course was unavailable.</p>
                        <p>2. Receiving a replacement Course of equal value to the unavailable Course at no extra cost to you.</p>
                        <h4>7.2 Subscription or membership service</h4>
                        <p>Membership or the subscription Services are fully earned upon payment of the membership fee by third party. There are no refunds for partially used periods.</p>
                        <h4>8. Cancellation</h4>
                        <p>You may choose to participate or not at your discretion. Your Subscription has been set for a specific period of time, which is non-transferable and non-returnable. Please contact your third party provider for more information on the length of your Subscription. If you terminate your subscription through the original provider of the subscription, your subscription will remain active until the end of your then-current subscription period—namely, the subscription period through which your provider paid before your termination. THERE WILL BE NO REFUND FOR ANY UNUSED PORTION OF YOUR SUBSCRIPTION.</p>
                        <h4>9. Indemnification</h4>
                        <p>You agree to indemnify and hold OVAL and its Representatives harmless from any and all losses (including without limitation attorneys’ fees) resulting from any claims based on or relating to your use, or the use of any individual using your password, of the OVAL Website or app. You further agree to indemnify and hold OVAL and its Representatives harmless from any and all losses resulting from claims of third parties, including without limitation attorneys’ fees, that result in whole or in part from violations by you, or any individual using your password, of any of the terms of this Agreement.</p>
                        <h4>10. Disputes</h4>
                        <p>This Agreement shall be governed by the laws of the State of Colorado. In the event that litigation results from or arises out of this Agreement or the performance thereof, both Parties agree to Arbitration with a single arbitrator qualified by the American Arbitration Association. The Parties agree to reimburse the prevailing Party’s reasonable attorneys’ fees, arbitration costs, and all other expenses, whether or not taxable by the arbitrator as costs, in addition to any other relief to which the prevailing Party may be entitled.</p>
                        <h4>11. Miscellaneous</h4>
                        <h4>11.1 Assignability</h4>
                        <p>This Agreement is personal to you, and you may not assign this Agreement or the rights and obligations thereunder to any third party or person.</p>
                        <h4>11.2 Waiver</h4>
                        <p>No waiver by either Party of any default shall be deemed as a waiver of prior or subsequent default of the same or other provisions of this Agreement.</p>
                        <h4>11.3 Severability</h4>
                        <p>If any term, clause, or provision hereof is held invalid or unenforceable by a court of competent jurisdiction, such invalidity shall not affect the validity or operation of any other term, clause, or provision, and such invalid term, clause, or provision shall be deemed to be severed from the Agreement.</p>
                        <h4>11.4 Survivability</h4>
                        <p>The ownership and intellectual property rights and license provisions set forth in this Agreement, and any other provisions that by their sense and context the Parties intend to have survive, shall survive the termination of this Agreement and any obligations hereunder for any reason.</p>
                        <h4>12. Third Party Intellectual Property Rights.</h4>
                        <p>Do Not Violate Third Party Intellectual Property Rights.</p>

                        <p>Without limiting the foregoing, you may not, and by using any or all of the Services, you agree not to use the Site or its Services and/or app to: (i) transmit material that is copyrighted, unless you are the copyright owner or have obtained the permission of the copyright owner to transmit it; (ii) transmit material that reveals trade secrets, unless you own them or have the permission of the owner to so transmit them; or (iii) transmit material that infringes on any Intellectual Property Rights (as defined below) of others or violates the privacy or rights of publicity of others. For purposes of this Agreement, the term “Intellectual Property Rights” means collectively, rights under patent, trademark, copyright and trade secret laws, any applications or registrations relating to such rights, and any other intellectual property or proprietary rights recognized in any country or jurisdiction worldwide, including, without limitation, the waiver of moral rights and similar rights.</p>
                        <p>All content, materials and software posted to or used in conjunction with the OVAL Website and/or app including, without limitation, text, graphics, logos, button icons, images and audio clips are the property of Company or its Licensors and are protected by U.S. and international copyright, trademarks and other proprietary rights and Intellectual Property Rights laws.</p>
                        <p>The compilation of all content on this Site is the exclusive property of the Company and its Licensors are protected by U.S. and international copyright laws. Except to the minimum extent otherwise expressly permitted under copyright law, no copying or exploitation of material from the Services is permitted without the express written permission of the Company and any other applicable copyright owner. You also may not resell the Services (or any part thereof). You acknowledge that you do not acquire any ownership rights by virtue of downloading copyrighted material from the Services. All rights not expressly granted hereunder are expressly reserved to Company. If you believe your rights under applicable copyright laws are being infringed, you may notify our designated agent by email us at info@ovalcare.com</p>
                        <h4>Spidering</h4>
                        <p>The use of any tools, programs, robotic algorithms or products to automatically download or “spider” the site or any of the pages of the site is expressly prohibited and infringes on Company’s copyrights.</p>
                        <h4>Trademarks</h4>
                        <p>OVAL is a registered trademark of NVBCO Group LLC DBA OVAL. The “look and feel” of the Company Site is also the Company's trademark and proprietary trade dress. This includes Company’s color combinations, button shapes, layout, and all other graphical and navigational elements. The Sites contain other registered and common law trademarks of Company, and third parties, in addition to those listed.</p>
                        <h4>Termination.</h4>
                        <p>OVAL may and will terminate Services immediately, if, in its sole discretion, the Company believes that your conduct fails to conform with this Section or this Agreement. Without limiting the foregoing, if you use, or attempt to use any or all of the Services for any purpose other than its intended purposes (including without limitation by tampering, hacking, modifying or otherwise corrupting the security or functionality of the Services), you may also be subject to civil and criminal liability.</p>
                        <h4>Contact Us</h4>
                        <p>If you have any questions or comments, or would like to discuss your subscription with our Customer Support staff, please contact us via the following information: info@oval.care</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
